language: node_js
node_js:
- '4.4'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm start > /dev/null &
- npm run update-webdriver
- sleep 1
script:
- node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots
  --browsers=Firefox

deploy:
  provider: heroku
  api_key:
    secure: munn+tvtTFOrL8RN2L1BHr7b9rZrafO5UhCOaKYQfoMqsBYdu0ugZ6jgVRuffZjW+A5aw/Ku8NO4bIjsvoOy6yvOwyzN1VHhBTSyW+tAp1KHHKNVHsW6F0lcCNUDuDUKUHZKJWMtssru7/z88KJT0/GZ4WvsyjppgaDpu/O6BHJtI2faoC8qaHVUSsI09336vBb9KhXuyaiiQcTvY0Aq9Dnrstx/AY/dtrQs/OBCHBwzlY8gBk1LQpefdTbSB/buKiPqb8dmrnaY6aFlftqZPV5ZIVw4o11EGBVbeji4iND2JTGd90cwVTxUEAAnr7sFUGRwXeQZWbLBHZ4kg9PI6lgF3aPZnxZ5x4IwN+If/fyvHvFa0gsI4hRiO/pmHbJ4wWA5jRqm8Sy+TMZkbiepwtSZV6KbFbRYyRvVJGJLFEWICobTVV3e0bf1qi+wdGLiHZ1owyEPUwzN5aUqMrpjS14+AB003AS7D5dO2N6I+bP561LK6CS6AhT8dfvqHrYn0yKaEwk4LCHT+WXwGMZMNRwEm7rJ8K0SUH9aorL3VQ7ZJAtu1t9USCIAuvK2LuU9S3VqT/hPlz7PkdQyq/N9+41eEWY8meOA0cQpSV0LFyPJwQ89UV9kL5wYRCgPA8NExee5rRQ33vcAFdT8Z4zb9S0C0aU0mjkuld6AoHGghIM=
  app: ui_code_challenge
  on:
    repo: ckeyes88/ui_code_challenge
