language: node_js
node_js:
- '4.4'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm start > /dev/null &
- npm run update-webdriver
- sleep 1
script:
- node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots
  --browsers=Firefox
deploy:
  provider: heroku
  api_key:
    secure: y0bsBIpv1UFWLDQj5RpD5YeOmShTN2NcHYRd/S9vHJAQXph+ydWhzbCW6n6z74Kjtl2N7z+X5xMUB4PB4TaHk/9I3rB3jyBaorHqUdoTwikKD9UaNE/45QbIO/LxZYYMX/Z0UAyIRSXFeiWI+ge2x94mhegQ1rR6X4q2fByhu0R2d0kYSC5vE1eH9F6dcHyBKDtVbc9G7ZozGgwW//USX/sDuTdPSB0nQVw8e9biI5lifaSoi95dPmgwZhWqyMwTPPqlZBuaj4nYZ8jo3QvMmpleyPAhB6E7bx2zIIML8G34xnSS0xqLm7waWBRMJPyFjRfK2H5e5M/mf20DjCoZWOxUR9DG7+OlrchhKiVkaJJ2IEPYXw+oMTcCLwKlI+pz4AIZf4jPQs8xfdDbkTmIBDz6Md+PglQTH5Jwt0jlLfTIJTYBJZXdPP8YlHWPdcCMDfesrgTSZu5jOL2jo7Tv/oaqsjWpOnFYLZtbqboBkUqRX6D8AJNqbTW38djrU1qZic+LclGrv10MVbPtp10MyNJowYYWTX05OkzUuyoUEJjXjsIHNxHODi/wsKi9q0Q4/nDqZLc0O14WYhQa5g1Zp+x2rLZfrVh2V82hYyppXwExgKPLNwsZPtS10raReAaJPfvUzT0HynCSOKzMTgs7iAfJCoAsF06gGyrKQPEHuwI=
  app: studio-hq-challenge
  on:
    repo: ckeyes88/ui_code_challenge
